export const TOAST_LIMIT = 1;
export const TOAST_REMOVE_DELAY = 4000;

export type ActionType = {
	ADD_TOAST: "ADD_TOAST";
	UPDATE_TOAST: "UPDATE_TOAST";
	DISMISS_TOAST: "DISMISS_TOAST";
	REMOVE_TOAST: "REMOVE_TOAST";
};
